<dl title="interface AnalyserNode : AudioNode" class="idl">
          <!--<dt> // Real-time frequency-domain data </dt>-->
          <dt>
            void getFloatFrequencyData()
          </dt>
          <dd>
            <p>
              Copies the <a>current frequency data</a> into the passed
              floating-point array. If the array has fewer elements than the
              <a><code>frequencyBinCount</code></a>, the excess elements will
              be dropped. If the array has more elements than the
              <a><code>frequencyBinCount</code></a>, the excess elements will
              be ignored.
            </p>
            <p>
              The frequency data are in dB units.
            </p>
            <dl class="parameters">
              <dt>
                Float32Array array
              </dt>
              <dd>
                This parameter is where the frequency-domain analysis data will
                be copied.
              </dd>
            </dl>
          </dd>
          <dt>
            void getByteFrequencyData()
          </dt>
          <dd>
            <p>
              Copies the <a>current frequency data</a> into the passed unsigned
              byte array. If the array has fewer elements than the
              <a><code>frequencyBinCount</code></a>, the excess elements will
              be dropped. If the array has more elements than the
              <a><code>frequencyBinCount</code></a>, the excess elements will
              be ignored.
            </p>
            <p>
              The values stored in the unsigned byte array are computed in the
              following way. Let \(Y[k]\) be the <a>current frequency data</a>
              as described in <a href="#fft-windowing-and-smoothing-over-time">FFT windowing and
              smoothing</a>. Then the byte value, \(b[k]\), is
            </p>
            <pre class="nohighlight">
                  $$
                    b[k] = \left\lfloor
                        \frac{255}{\mbox{dB}_{max} - \mbox{dB}_{min}}
                        \left(Y[k] - \mbox{dB}_{min}\right)
                      \right\rfloor
                  $$
            </pre>
            <p>
              where \(\mbox{dB}_{min}\) is <code><a>minDecibels</a></code> and
              \(\mbox{dB}_{max}\) is <code><a>maxDecibels</a></code>. If
              \(b[k]\) lies outside the range of 0 to 255, \(b[k]\) is clipped
              to lie in that range.
            </p>
            <dl class="parameters">
              <dt>
                Uint8Array array
              </dt>
              <dd>
                This parameter is where the frequency-domain analysis data will
                be copied.
              </dd>
            </dl>
          </dd><!--<dt>// Real-time waveform data </dt>-->
          <dt>
            void getFloatTimeDomainData()
          </dt>
          <dd>
            <p>
              Copies the current down-mixed time-domain (waveform) data into
              the passed floating-point array. If the array has fewer elements
              than the value of <a><code>fftSize</code></a>, the excess
              elements will be dropped. If the array has more elements than
              <a><code>fftSize</code></a>, the excess elements will be ignored.
            </p>
            <dl class="parameters">
              <dt>
                Float32Array array
              </dt>
              <dd>
                This parameter is where the time-domain sample data will be
                copied.
              </dd>
            </dl>
          </dd>
          <dt>
            void getByteTimeDomainData()
          </dt>
          <dd>
            <p>
              Copies the current down-mixed time-domain (waveform) data into
              the passed unsigned byte array. If the array has fewer elements
              than the value of <a><code>fftSize</code></a>, the excess
              elements will be dropped. If the array has more elements than
              <a><code>fftSize</code></a>, the excess elements will be ignored.
            </p>
            <p>
              The values stored in the unsigned byte array are computed in the
              following way. Let \(x[k]\) be the time-domain data. Then the
              byte value, \(b[k]\), is
            </p>
            <pre class="nohighlight">
              $$
                b[k] = \left\lfloor 128(1 + x[k]) \right\rfloor.
              $$
            </pre>
            <p>
              If \(b[k]\) lies outside the range 0 to 255, \(b[k]\) is clipped
              to lie in that range.
            </p>
            <dl class="parameters">
              <dt>
                Uint8Array array
              </dt>
              <dd>
                This parameter is where the time-domain sample data will be
                copied.
              </dd>
            </dl>
          </dd>
          <dt>
            attribute unsigned long fftSize
          </dt>
          <dd>
            The size of the FFT used for frequency-domain analysis.
            <span class="synchronous">This must be a power of two in the range
            32 to 32768, otherwise an IndexSizeError exception MUST be
            thrown</span>. The default value is 2048. Note that large FFT sizes
            can be costly to compute.
          </dd>
          <dt>
            readonly attribute unsigned long frequencyBinCount
          </dt>
          <dd>
            Half the FFT size.
          </dd>
          <dt>
            attribute float minDecibels
          </dt>
          <dd>
            <dfn id="minDecibels">minDecibels</dfn> is the minimum power value
            in the scaling range for the FFT analysis data for conversion to
            unsigned byte values. The default value is -100. <span class="synchronous">If the value of this attribute is set to a value more
            than or equal to <code><a>maxDecibels</a></code>, an IndexSizeError
            exception MUST be thrown.</span>
          </dd>
          <dt>
            attribute float maxDecibels
          </dt>
          <dd>
            <dfn id="maxDecibels">maxDecibels</dfn> is the maximum power value
            in the scaling range for the FFT analysis data for conversion to
            unsigned byte values. The default value is -30. <span class="synchronous">If the value of this attribute is set to a value less
            than or equal to <code><a>minDecibels</a></code>, an IndexSizeError
            exception MUST be thrown.</span>
          </dd>
          <dt>
            attribute float smoothingTimeConstant
          </dt>
          <dd>
            A value from 0 -&gt; 1 where 0 represents no time averaging with
            the last analysis frame. The default value is 0.8. <span class="synchronous">If the value of this attribute is set to a value less
            than 0 or more than 1, an IndexSizeError exception MUST be
            thrown.</span>
          </dd>
        </dl>