<dl title="interface AudioListener" class="idl">
          <dt>
            readonly attribute AudioParam positionX
          </dt>
          <dd>
            Sets the x coordinate position of the audio listener in a 3D
            Cartesian coordinate space. <a><code>PannerNode</code></a> objects
            use this position relative to individual audio sources for
            spatialization. The default value is 0. This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam positionY
          </dt>
          <dd>
            Sets the y coordinate position of the audio listener in a 3D
            Cartesian coordinate space. The default value is 0. This parameter
            is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam positionZ
          </dt>
          <dd>
            Sets the z coordinate position of the audio listener in a 3D
            Cartesian coordinate space. The default value is 0. This parameter
            is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam forwardX
          </dt>
          <dd>
            The <code>forwardX, forwardY, forwardZ</code> parameters represent
            a direction vector in 3D space. Both a <code>forward</code> vector
            and an <code>up</code> vector are used to determine the orientation
            of the listener. In simple human terms, the <code>forward</code>
            vector represents which direction the person&apos;s nose is pointing.
            The <code>up</code> vector represents the direction the top of a
            person&apos;s head is pointing. These values are expected to be linearly
            independent (at right angles to each other), and unpredictable
            behavior may result if they are not. For normative requirements of
            how these values are to be interpreted, see the <a href="#Spatialization">spatialization section</a>.
          </dd>
          <dd>
            Sets the x coordinate component of the forward direction the
            listener is pointing in 3D Cartesian coordinate space. The default
            value is 0. This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam forwardY
          </dt>
          <dd>
            Sets the y coordinate component of the forward direction the
            listener is pointing in 3D Cartesian coordinate space. The default
            value is 0. This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam forwardZ
          </dt>
          <dd>
            Sets the z coordinate component of the forward direction the
            listener is pointing in 3D Cartesian coordinate space. The default
            value is 0. This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam upX
          </dt>
          <dd>
            The <code>upX, upY, upZ</code> parameters represent a direction
            vector in 3D space, indicating the direction of &quot;up&quot; to the
            listener. For normative requirements of how these values are to be
            interpreted, see the <a href="#Spatialization">spatialization
            section</a>.
          </dd>
          <dd>
            Sets the x coordinate component of the up direction the listener is
            pointing in 3D Cartesian coordinate space. The default value is 0.
            This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam upY
          </dt>
          <dd>
            Sets the y coordinate component of the up direction the listener is
            pointing in 3D Cartesian coordinate space. The default value is 0.
            This parameter is a-rate.
          </dd>
          <dt>
            readonly attribute AudioParam upZ
          </dt>
          <dd>
            Sets the z coordinate component of the up direction the listener is
            pointing in 3D Cartesian coordinate space. The default value is 0.
            This parameter is a-rate.
          </dd>
          <dt>
            void setPosition(float x, float y, float z)
          </dt>
          <dd>
            <p>
              This method is DEPRECATED. It is equivalent to setting
              <code>positionX</code>, <code>positionY</code>, and
              <code>positionZ</code> AudioParams directly.
            </p>
            <p>
              Sets the position of the listener in a 3D cartesian coordinate
              space. <a><code>PannerNode</code></a> objects use this position
              relative to individual audio sources for spatialization.
            </p>
            <p>
              The <code>x, y, z</code> parameters represent the coordinates in
              3D space.
            </p>
            <p>
              The default value is (0,0,0)
            </p>
          </dd>
          <dt>
            void setOrientation(float x, float y, float z, float xUp, float
            yUp, float zUp)
          </dt>
          <dd>
            <p>
              This method is DEPRECATED. It is equivalent to setting
              <code>orientationX</code>, <code>orientationY</code>,
              <code>orientationZ</code>, <code>upX</code>, <code>upY</code>,
              and <code>upZ</code> AudioParams directly.
            </p>
            <p>
              Describes which direction the listener is pointing in the 3D
              cartesian coordinate space. Both a <b>front</b> vector and an
              <b>up</b> vector are provided. In simple human terms, the
              <b>front</b> vector represents which direction the person&apos;s nose
              is pointing. The <b>up</b> vector represents the direction the
              top of a person&apos;s head is pointing. These values are expected to
              be linearly independent (at right angles to each other). For
              normative requirements of how these values are to be interpreted,
              see the <a href="#Spatialization">spatialization section</a>.
            </p>
            <p>
              The <code>x, y, z</code> parameters represent a <b>front</b>
              direction vector in 3D space, with the default value being
              (0,0,-1).
            </p>
            <p>
              The <code>xUp, yUp, zUp</code> parameters represent an <b>up</b>
              direction vector in 3D space, with the default value being
              (0,1,0).
            </p>
          </dd>
        </dl>