<pre id="enum-BiquadFilterType" class="idl">
enum BiquadFilterType {
    "lowpass",
    "highpass",
    "bandpass",
    "lowshelf",
    "highshelf",
    "peaking",
    "notch",
    "allpass"
};
</pre>
<table class="simple">
  <tr>
    <th colspan="2">Enumeration description:</th>
  </tr>
  <tr>
    <td><dfn for="BiquadFilterType">lowpass</dfn></td>
    <td><p>
              A <a href="https://en.wikipedia.org/wiki/Low-pass_filter">lowpass
              filter</a> allows frequencies below the cutoff frequency to pass
              through and attenuates frequencies above the cutoff. It
              implements a standard second-order resonant lowpass filter with
              12dB/octave rolloff.
            </p>
            <blockquote>
              <dl>
                <dt>
                  frequency
                </dt>
                <dd>
                  The cutoff frequency
                </dd>
                <dt>
                  Q
                </dt>
                <dd>
                  Controls how peaked the response will be at the cutoff
                  frequency. A large value makes the response more peaked.
                  Please note that for this filter type, this value is not a
                  traditional Q, but is a resonance value in decibels.
                </dd>
                <dt>
                  gain
                </dt>
                <dd>
                  Not used in this filter type
                </dd>
              </dl>
            </blockquote></td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">highpass</dfn></td>
    <td>The cutoff frequency</td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">bandpass</dfn></td>
    <td>Controls how peaked the response will be at the cutoff
                  frequency. A large value makes the response more peaked.
                  Please note that for this filter type, this value is not a
                  traditional Q, but is a resonance value in decibels.</td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">lowshelf</dfn></td>
    <td>Not used in this filter type</td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">highshelf</dfn></td>
    <td><p>
              A <a href="https://en.wikipedia.org/wiki/High-pass_filter">highpass
              filter</a> is the opposite of a lowpass filter. Frequencies above
              the cutoff frequency are passed through, but frequencies below
              the cutoff are attenuated. It implements a standard second-order
              resonant highpass filter with 12dB/octave rolloff.
            </p>
            <blockquote>
              <dl>
                <dt>
                  frequency
                </dt>
                <dd>
                  The cutoff frequency below which the frequencies are
                  attenuated
                </dd>
                <dt>
                  Q
                </dt>
                <dd>
                  Controls how peaked the response will be at the cutoff
                  frequency. A large value makes the response more peaked.
                  Please note that for this filter type, this value is not a
                  traditional Q, but is a resonance value in decibels.
                </dd>
                <dt>
                  gain
                </dt>
                <dd>
                  Not used in this filter type
                </dd>
              </dl>
            </blockquote></td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">peaking</dfn></td>
    <td>The cutoff frequency below which the frequencies are
                  attenuated</td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">notch</dfn></td>
    <td>Controls how peaked the response will be at the cutoff
                  frequency. A large value makes the response more peaked.
                  Please note that for this filter type, this value is not a
                  traditional Q, but is a resonance value in decibels.</td>
</tr>
    <tr>
    <td><dfn for="BiquadFilterType">allpass</dfn></td>
    <td>Not used in this filter type</td>
</tr>
</table>